"""Derive an ISO country code from an opportunity location string.

The crawler location field is free text, so this deliberately uses a small,
deterministic set of high-confidence aliases and cities instead of a geocoding
service. It is dependency-free so it can run in ingestion and maintenance jobs.
"""

from __future__ import annotations

import re

_REMOTE_ONLY_VALUES = frozenset(
    {
        "remote",
        "remote only",
        "fully remote",
        "online",
        "online only",
        "anywhere",
        "anywhere in the world",
        "work from home",
        "wfh",
        "worldwide",
        "global",
        "remote worldwide",
        "remote global",
        "remote anywhere",
        "online worldwide",
    }
)

# Keep this list to names and broadly unambiguous aliases. In particular,
# short ISO codes (other than the common US/UK/UAE forms below) are omitted:
# a value such as ", IN" could mean either India or Indiana.
_COUNTRY_ALIASES: tuple[tuple[str, str], ...] = (
    ("united states of america", "US"),
    ("united states", "US"),
    ("u.s.a.", "US"),
    ("u.s.", "US"),
    ("usa", "US"),
    ("us", "US"),
    ("america", "US"),
    ("united kingdom", "GB"),
    ("great britain", "GB"),
    ("britain", "GB"),
    ("england", "GB"),
    ("scotland", "GB"),
    ("wales", "GB"),
    ("u.k.", "GB"),
    ("uk", "GB"),
    ("united arab emirates", "AE"),
    ("uae", "AE"),
    ("india", "IN"),
    ("bharat", "IN"),
    ("germany", "DE"),
    ("deutschland", "DE"),
    ("canada", "CA"),
    ("australia", "AU"),
    ("singapore", "SG"),
    ("france", "FR"),
    ("the netherlands", "NL"),
    ("netherlands", "NL"),
    ("holland", "NL"),
    ("republic of ireland", "IE"),
    ("ireland", "IE"),
    ("japan", "JP"),
    ("people's republic of china", "CN"),
    ("china", "CN"),
    ("prc", "CN"),
    ("hong kong", "HK"),
    ("south korea", "KR"),
    ("republic of korea", "KR"),
    ("taiwan", "TW"),
    ("israel", "IL"),
    ("poland", "PL"),
    ("spain", "ES"),
    ("italy", "IT"),
    ("brazil", "BR"),
    ("brasil", "BR"),
    ("mexico", "MX"),
    ("méxico", "MX"),
    ("austria", "AT"),
    ("belgium", "BE"),
    ("switzerland", "CH"),
    ("sweden", "SE"),
    ("norway", "NO"),
    ("denmark", "DK"),
    ("finland", "FI"),
    ("portugal", "PT"),
    ("greece", "GR"),
    ("czech republic", "CZ"),
    ("czechia", "CZ"),
    ("romania", "RO"),
    ("hungary", "HU"),
    ("slovakia", "SK"),
    ("slovenia", "SI"),
    ("croatia", "HR"),
    ("serbia", "RS"),
    ("bulgaria", "BG"),
    ("estonia", "EE"),
    ("latvia", "LV"),
    ("lithuania", "LT"),
    ("ukraine", "UA"),
    ("russia", "RU"),
    ("russian federation", "RU"),
    ("turkey", "TR"),
    ("türkiye", "TR"),
    ("turkiye", "TR"),
    ("saudi arabia", "SA"),
    ("qatar", "QA"),
    ("kuwait", "KW"),
    ("oman", "OM"),
    ("bahrain", "BH"),
    ("egypt", "EG"),
    ("south africa", "ZA"),
    ("nigeria", "NG"),
    ("kenya", "KE"),
    ("ghana", "GH"),
    ("morocco", "MA"),
    ("tunisia", "TN"),
    ("algeria", "DZ"),
    ("pakistan", "PK"),
    ("bangladesh", "BD"),
    ("sri lanka", "LK"),
    ("nepal", "NP"),
    ("indonesia", "ID"),
    ("malaysia", "MY"),
    ("thailand", "TH"),
    ("vietnam", "VN"),
    ("philippines", "PH"),
    ("new zealand", "NZ"),
    ("argentina", "AR"),
    ("chile", "CL"),
    ("colombia", "CO"),
    ("peru", "PE"),
    ("uruguay", "UY"),
    ("venezuela", "VE"),
    ("ecuador", "EC"),
    ("costa rica", "CR"),
    ("panama", "PA"),
    ("dominican republic", "DO"),
    ("puerto rico", "PR"),
    ("guatemala", "GT"),
)

# Major technology hubs, including the locations most frequently encountered
# in Indian ATS listings. Explicit country names always take precedence over
# this city fallback.
_CITY_COUNTRIES: tuple[tuple[str, str], ...] = (
    # India
    ("bengaluru", "IN"),
    ("bangalore", "IN"),
    ("mumbai", "IN"),
    ("bombay", "IN"),
    ("new delhi", "IN"),
    ("delhi", "IN"),
    ("hyderabad", "IN"),
    ("chennai", "IN"),
    ("madras", "IN"),
    ("pune", "IN"),
    ("kolkata", "IN"),
    ("calcutta", "IN"),
    ("gurugram", "IN"),
    ("gurgaon", "IN"),
    ("noida", "IN"),
    ("greater noida", "IN"),
    ("ahmedabad", "IN"),
    ("jaipur", "IN"),
    ("kochi", "IN"),
    ("cochin", "IN"),
    ("chandigarh", "IN"),
    ("indore", "IN"),
    ("coimbatore", "IN"),
    ("thiruvananthapuram", "IN"),
    ("trivandrum", "IN"),
    ("lucknow", "IN"),
    ("bhubaneswar", "IN"),
    ("visakhapatnam", "IN"),
    ("vizag", "IN"),
    ("nagpur", "IN"),
    ("surat", "IN"),
    ("vadodara", "IN"),
    ("baroda", "IN"),
    ("mysuru", "IN"),
    ("mysore", "IN"),
    ("nashik", "IN"),
    ("patna", "IN"),
    ("kanpur", "IN"),
    ("ludhiana", "IN"),
    ("mohali", "IN"),
    ("dehradun", "IN"),
    ("madurai", "IN"),
    # United States
    ("new york city", "US"),
    ("new york", "US"),
    ("san francisco", "US"),
    ("san jose", "US"),
    ("palo alto", "US"),
    ("mountain view", "US"),
    ("seattle", "US"),
    ("austin", "US"),
    ("boston", "US"),
    ("chicago", "US"),
    ("los angeles", "US"),
    ("san diego", "US"),
    ("denver", "US"),
    ("atlanta", "US"),
    ("miami", "US"),
    ("dallas", "US"),
    ("houston", "US"),
    ("washington dc", "US"),
    ("washington, d.c.", "US"),
    # United Kingdom
    ("london", "GB"),
    ("manchester", "GB"),
    ("edinburgh", "GB"),
    ("cambridge", "GB"),
    ("oxford", "GB"),
    ("birmingham", "GB"),
    ("bristol", "GB"),
    ("glasgow", "GB"),
    ("leeds", "GB"),
    # Canada
    ("toronto", "CA"),
    ("vancouver", "CA"),
    ("montreal", "CA"),
    ("montréal", "CA"),
    ("ottawa", "CA"),
    ("waterloo", "CA"),
    ("calgary", "CA"),
    ("quebec city", "CA"),
    # Europe
    ("berlin", "DE"),
    ("munich", "DE"),
    ("münchen", "DE"),
    ("hamburg", "DE"),
    ("frankfurt", "DE"),
    ("cologne", "DE"),
    ("köln", "DE"),
    ("stuttgart", "DE"),
    ("ulm", "DE"),
    ("amsterdam", "NL"),
    ("eindhoven", "NL"),
    ("rotterdam", "NL"),
    ("utrecht", "NL"),
    ("the hague", "NL"),
    ("paris", "FR"),
    ("lyon", "FR"),
    ("toulouse", "FR"),
    ("grenoble", "FR"),
    ("nantes", "FR"),
    ("dublin", "IE"),
    ("cork", "IE"),
    ("galway", "IE"),
    ("limerick", "IE"),
    ("madrid", "ES"),
    ("barcelona", "ES"),
    ("valencia", "ES"),
    ("malaga", "ES"),
    ("málaga", "ES"),
    ("milan", "IT"),
    ("milano", "IT"),
    ("rome", "IT"),
    ("roma", "IT"),
    ("turin", "IT"),
    ("torino", "IT"),
    ("warsaw", "PL"),
    ("krakow", "PL"),
    ("kraków", "PL"),
    ("wroclaw", "PL"),
    ("wrocław", "PL"),
    ("gdansk", "PL"),
    ("gdańsk", "PL"),
    ("zurich", "CH"),
    ("zürich", "CH"),
    ("geneva", "CH"),
    ("basel", "CH"),
    ("lausanne", "CH"),
    ("stockholm", "SE"),
    ("gothenburg", "SE"),
    ("malmö", "SE"),
    ("copenhagen", "DK"),
    ("aarhus", "DK"),
    ("oslo", "NO"),
    ("helsinki", "FI"),
    ("lisbon", "PT"),
    ("porto", "PT"),
    ("brussels", "BE"),
    ("antwerp", "BE"),
    ("ghent", "BE"),
    ("vienna", "AT"),
    ("prague", "CZ"),
    ("brno", "CZ"),
    ("tbilisi", "GE"),
    ("batumi", "GE"),
    ("bucharest", "RO"),
    ("cluj", "RO"),
    ("budapest", "HU"),
    ("athens", "GR"),
    ("thessaloniki", "GR"),
    ("tallinn", "EE"),
    ("riga", "LV"),
    ("vilnius", "LT"),
    ("kyiv", "UA"),
    ("kiev", "UA"),
    ("lviv", "UA"),
    # Middle East and Africa
    ("dubai", "AE"),
    ("abu dhabi", "AE"),
    ("riyadh", "SA"),
    ("jeddah", "SA"),
    ("doha", "QA"),
    ("tel aviv", "IL"),
    ("jerusalem", "IL"),
    ("haifa", "IL"),
    ("istanbul", "TR"),
    ("ankara", "TR"),
    ("izmir", "TR"),
    ("cairo", "EG"),
    ("alexandria", "EG"),
    ("cape town", "ZA"),
    ("johannesburg", "ZA"),
    ("pretoria", "ZA"),
    ("lagos", "NG"),
    ("abuja", "NG"),
    ("nairobi", "KE"),
    ("accra", "GH"),
    ("casablanca", "MA"),
    ("rabat", "MA"),
    # Asia-Pacific
    ("kuala lumpur", "MY"),
    ("penang", "MY"),
    ("johor bahru", "MY"),
    ("jakarta", "ID"),
    ("bandung", "ID"),
    ("surabaya", "ID"),
    ("bangkok", "TH"),
    ("chiang mai", "TH"),
    ("hanoi", "VN"),
    ("ho chi minh city", "VN"),
    ("saigon", "VN"),
    ("da nang", "VN"),
    ("manila", "PH"),
    ("cebu", "PH"),
    ("beijing", "CN"),
    ("shanghai", "CN"),
    ("shenzhen", "CN"),
    ("guangzhou", "CN"),
    ("hangzhou", "CN"),
    ("chengdu", "CN"),
    ("tokyo", "JP"),
    ("osaka", "JP"),
    ("kyoto", "JP"),
    ("yokohama", "JP"),
    ("fukuoka", "JP"),
    ("seoul", "KR"),
    ("busan", "KR"),
    ("taipei", "TW"),
    ("hsinchu", "TW"),
    ("kaohsiung", "TW"),
    ("sydney", "AU"),
    ("melbourne", "AU"),
    ("brisbane", "AU"),
    ("perth", "AU"),
    ("canberra", "AU"),
    ("adelaide", "AU"),
    ("auckland", "NZ"),
    ("wellington", "NZ"),
    ("christchurch", "NZ"),
    # Latin America
    ("são paulo", "BR"),
    ("sao paulo", "BR"),
    ("rio de janeiro", "BR"),
    ("belo horizonte", "BR"),
    ("curitiba", "BR"),
    ("mexico city", "MX"),
    ("guadalajara", "MX"),
    ("monterrey", "MX"),
    ("buenos aires", "AR"),
    ("córdoba", "AR"),
    ("cordoba", "AR"),
    ("santiago", "CL"),
    ("bogotá", "CO"),
    ("bogota", "CO"),
    ("medellín", "CO"),
    ("medellin", "CO"),
    ("lima", "PE"),
    ("san josé", "CR"),
    ("san jose", "CR"),
)

_US_STATE_NAMES: tuple[str, ...] = (
    "alabama",
    "alaska",
    "arizona",
    "arkansas",
    "california",
    "colorado",
    "connecticut",
    "delaware",
    "district of columbia",
    "florida",
    "georgia",
    "hawaii",
    "idaho",
    "illinois",
    "indiana",
    "iowa",
    "kansas",
    "kentucky",
    "louisiana",
    "maine",
    "maryland",
    "massachusetts",
    "michigan",
    "minnesota",
    "mississippi",
    "missouri",
    "montana",
    "nebraska",
    "nevada",
    "new hampshire",
    "new jersey",
    "new mexico",
    "new york",
    "north carolina",
    "north dakota",
    "ohio",
    "oklahoma",
    "oregon",
    "pennsylvania",
    "rhode island",
    "south carolina",
    "south dakota",
    "tennessee",
    "texas",
    "utah",
    "vermont",
    "virginia",
    "washington",
    "west virginia",
    "wisconsin",
    "wyoming",
)

_US_STATE_ABBREVIATIONS = (
    "AL",
    "AK",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "DC",
    "FL",
    "GA",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VT",
    "VA",
    "WA",
    "WV",
    "WI",
    "WY",
)


def _phrase_pattern(value: str) -> re.Pattern[str]:
    """Return a case-insensitive whole-phrase matcher for a location token."""
    escaped = re.escape(value).replace(r"\ ", r"\s+")
    return re.compile(rf"(?<![A-Za-z0-9]){escaped}(?![A-Za-z0-9])", re.IGNORECASE)


def _compile_matchers(
    entries: tuple[tuple[str, str], ...],
) -> tuple[tuple[str, re.Pattern[str]], ...]:
    return tuple((country, _phrase_pattern(value)) for value, country in entries)


_COUNTRY_MATCHERS = _compile_matchers(_COUNTRY_ALIASES)
_CITY_MATCHERS = _compile_matchers(_CITY_COUNTRIES)
_US_STATE_MATCHERS = _compile_matchers(tuple((state, "US") for state in _US_STATE_NAMES))
_US_STATE_ABBREVIATION_RE = re.compile(
    rf",\s*(?:{'|'.join(_US_STATE_ABBREVIATIONS)})(?![A-Za-z0-9])",
    re.IGNORECASE,
)


def _first_match(text: str, matchers: tuple[tuple[str, re.Pattern[str]], ...]) -> str | None:
    """Find the first, then longest, matching entry in a deterministic matcher set."""
    winner: tuple[int, int, int, str] | None = None

    for priority, (country, pattern) in enumerate(matchers):
        match = pattern.search(text)
        if match is None:
            continue

        candidate = (match.start(), -(match.end() - match.start()), priority, country)
        if winner is None or candidate < winner:
            winner = candidate

    return winner[3] if winner is not None else None


def _remote_key(location: str) -> str:
    return re.sub(r"[\W_]+", " ", location.casefold()).strip()


def derive_country(location: str | None) -> str | None:
    """Return a high-confidence ISO-3166 alpha-2 country code for a location.

    Explicit country names and aliases are always preferred over city and U.S.
    state fallbacks. Unknown and remote-only locations intentionally remain
    None because remote eligibility is tracked separately by is_remote.
    """
    if location is None:
        return None

    text = location.strip()
    if not text or _remote_key(text) in _REMOTE_ONLY_VALUES:
        return None

    explicit_country = _first_match(text, _COUNTRY_MATCHERS)
    if explicit_country is not None:
        return explicit_country

    city_country = _first_match(text, _CITY_MATCHERS)
    if city_country is not None:
        return city_country

    state_country = _first_match(text, _US_STATE_MATCHERS)
    if state_country is not None or _US_STATE_ABBREVIATION_RE.search(text) is not None:
        return "US"

    return None
